# Generated by Django 5.1.1 on 2024-09-18 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_is_sale_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_sale',
        ),
    ]
